apiVersion: v1
kind: Pod
metadata:
  name: itest
  labels:
    app: itest
spec:
  containers:
  - name: itest
    image: "iostio/iost-node:$TAG"
    imagePullPolicy: "IfNotPresent"
    command: ['/bin/bash', '-c', 'sleep infinity']
    resources:
      limits:
        cpu: 500m
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
      - name: config-volume
        mountPath: /etc/itest
  volumes:
    - name: config-volume
      configMap:
        name: itest-config
